# syntax=docker/dockerfile:1
FROM ruby:__RUBY_VERSION__

# Rails app lives here
WORKDIR /app

# Install base packages
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    libvips-dev \
    postgresql-client

ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

# Install application gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy application code
COPY . .

# Add a script to be executed every time the container starts.
ENTRYPOINT ["/app/bin/docker-entrypoint-dev"]
EXPOSE 3000

# Configure the main process to run when running the image
CMD ["./bin/rails", "server", "-b", "0.0.0.0"]
